#! /usr/bin/env python2
import os

from autoindex.main import main

try:
    from raven import Client
    HAS_RAVEN = True
except ImportError:
    HAS_RAVEN = False


if __name__ == '__main__':
    try:
        main()
    except Exception:
        if HAS_RAVEN and 'SENTRY_DSN' in os.environ:
            client = Client()
            client.captureException()
